//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTE.eAdapter.NativeDataService {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceAction", Namespace="http://schemas.datacontract.org/2004/07/Enterprise.DataTransfer.Native.Service")]
    public enum ServiceAction : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Update = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Retrieve = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.cargowise.com/NativeDataService", ConfigurationName="NativeDataService.EnterpriseNativeDataService")]
    public interface EnterpriseNativeDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cargowise.com/NativeDataService/EnterpriseNativeDataService/RetrieveDa" +
            "ta", ReplyAction="http://www.cargowise.com/NativeDataService/EnterpriseNativeDataService/RetrieveDa" +
            "taResponse")]
        string RetrieveData(string retrieveDataRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cargowise.com/NativeDataService/EnterpriseNativeDataService/Retrieve", ReplyAction="http://www.cargowise.com/NativeDataService/EnterpriseNativeDataService/RetrieveRe" +
            "sponse")]
        System.Xml.Linq.XElement Retrieve(System.Xml.Linq.XElement retrieveDataRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cargowise.com/NativeDataService/EnterpriseNativeDataService/UpdateData" +
            "", ReplyAction="http://www.cargowise.com/NativeDataService/EnterpriseNativeDataService/UpdateData" +
            "Response")]
        string UpdateData(string updateDataRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cargowise.com/NativeDataService/EnterpriseNativeDataService/Update", ReplyAction="http://www.cargowise.com/NativeDataService/EnterpriseNativeDataService/UpdateResp" +
            "onse")]
        System.Xml.Linq.XElement Update(System.Xml.Linq.XElement updateDataRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cargowise.com/NativeDataService/EnterpriseNativeDataService/Service", ReplyAction="http://www.cargowise.com/NativeDataService/EnterpriseNativeDataService/ServiceRes" +
            "ponse")]
        System.Xml.Linq.XElement Service(System.Xml.Linq.XElement request, OTE.eAdapter.NativeDataService.ServiceAction action);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EnterpriseNativeDataServiceChannel : OTE.eAdapter.NativeDataService.EnterpriseNativeDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EnterpriseNativeDataServiceClient : System.ServiceModel.ClientBase<OTE.eAdapter.NativeDataService.EnterpriseNativeDataService>, OTE.eAdapter.NativeDataService.EnterpriseNativeDataService {
        
        public EnterpriseNativeDataServiceClient() {
        }
        
        public EnterpriseNativeDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EnterpriseNativeDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EnterpriseNativeDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EnterpriseNativeDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string RetrieveData(string retrieveDataRequest) {
            return base.Channel.RetrieveData(retrieveDataRequest);
        }
        
        public System.Xml.Linq.XElement Retrieve(System.Xml.Linq.XElement retrieveDataRequest) {
            return base.Channel.Retrieve(retrieveDataRequest);
        }
        
        public string UpdateData(string updateDataRequest) {
            return base.Channel.UpdateData(updateDataRequest);
        }
        
        public System.Xml.Linq.XElement Update(System.Xml.Linq.XElement updateDataRequest) {
            return base.Channel.Update(updateDataRequest);
        }
        
        public System.Xml.Linq.XElement Service(System.Xml.Linq.XElement request, OTE.eAdapter.NativeDataService.ServiceAction action) {
            return base.Channel.Service(request, action);
        }
    }
}
